import { tool } from "@langchain/core/tools";
import { z } from "zod";
import { query, queryOne } from "../db";
import fs from "fs";
import path from "path";
import PptxGenJS from "pptxgenjs";
import { runEmitter } from "../services/sse.service";

// Make sure public downloads directory exists
const DOWNLOADS_DIR = path.join(process.cwd(), "public", "downloads");
if (!fs.existsSync(DOWNLOADS_DIR)) {
  fs.mkdirSync(DOWNLOADS_DIR, { recursive: true });
}

export function getArtifactTools(tenantId: string, workflowId: string, runId?: string) {
  
  // Helper to get or create a default project for the tenant
  const getProjectId = async () => {
    let proj = await queryOne('SELECT id FROM projects WHERE workspace_id IN (SELECT id FROM workspaces WHERE tenant_id = $1) LIMIT 1', [tenantId]);
    if (!proj) {
      // Create default workspace and project if missing
      const [ws] = await query('INSERT INTO workspaces (tenant_id, name) VALUES ($1, $2) RETURNING id', [tenantId, 'Default Workspace']);
      const [p] = await query('INSERT INTO projects (workspace_id, name) VALUES ($1, $2) RETURNING id', [ws.id, 'General Project']);
      proj = p;
    }
    return proj.id;
  };

  const generatePresentationTool = tool(
    async ({ title, slides }) => {
      try {
        const pres = new PptxGenJS();
        pres.layout = "LAYOUT_16x9";
        
        // Title Slide
        let slide = pres.addSlide();
        slide.addText(title, { x: 1, y: 2, w: "80%", h: 1.5, fontSize: 44, bold: true, align: "center", color: "363636" });
        slide.addText("Generated by Chatbolt OS", { x: 1, y: 3.5, w: "80%", h: 1, fontSize: 24, align: "center", color: "666666" });

        // Content Slides
        for (const s of slides) {
          slide = pres.addSlide();
          slide.addText(s.title, { x: 0.5, y: 0.5, w: "90%", h: 1, fontSize: 32, bold: true, color: "007acc" });
          
          if (s.bulletPoints && s.bulletPoints.length > 0) {
            slide.addText(
              s.bulletPoints.map(bp => ({ text: bp, options: { bullet: true } })),
              { x: 0.5, y: 1.8, w: "90%", h: 3.5, fontSize: 20, color: "363636", valign: "top" }
            );
          } else if (s.content) {
            slide.addText(s.content, { x: 0.5, y: 1.8, w: "90%", h: 3.5, fontSize: 20, color: "363636", valign: "top" });
          }
        }

        const fileName = `Presentation_${Date.now()}.pptx`;
        const filePath = path.join(DOWNLOADS_DIR, fileName);
        
        await pres.writeFile({ fileName: filePath });
        const downloadUrl = `/downloads/${fileName}`;
        
        const projectId = await getProjectId();
        
        // Save to artifacts table
        const [artifact] = await query(`
          INSERT INTO artifacts (project_id, tenant_id, name, artifact_type, metadata)
          VALUES ($1, $2, $3, $4, $5)
          RETURNING *
        `, [
          projectId, 
          tenantId, 
          title, 
          'presentation', 
          JSON.stringify({ downloadUrl, source_workflow: workflowId })
        ]);

        // Save a text version in artifact_versions for context
        await query(`
          INSERT INTO artifact_versions (artifact_id, version_number, raw_contents, change_description, summary, created_by)
          VALUES ($1, 1, $2, 'Initial generation', 'Generated PPTX with ' || $3 || ' slides', 'system')
        `, [artifact.id, JSON.stringify(slides, null, 2), slides.length]);

        // Emit artifact:created event
        if (runId) {
          runEmitter.emitEvent(runId, 'artifact:created' as any, {
            artifactId: artifact.id,
            filename: artifact.name,
            mimeType: 'presentation',
            downloadUrl
          });
        }

        return `Successfully generated Presentation PPTX! Download URL: ${downloadUrl} (Artifact ID: ${artifact.id})`;
      } catch (err: any) {
        return `Failed to generate presentation: ${err.message}`;
      }
    },
    {
      name: "generate_presentation",
      description: "Generates a real, downloadable .pptx PowerPoint file. Provide a title and an array of slides.",
      schema: z.object({
        title: z.string().describe("The main title of the presentation"),
        slides: z.array(z.object({
          title: z.string().describe("The title of the slide"),
          bulletPoints: z.array(z.string()).optional().describe("Bullet points for the slide"),
          content: z.string().optional().describe("Paragraph content if bullet points are not used")
        })).describe("The content of the slides")
      }),
    }
  );

  const generateWebsiteTool = tool(
    async ({ appName, files }) => {
      try {
        const projectId = await getProjectId();
        
        // Combine into one large metadata artifact or zip
        // For Chatbolt, we can save a "website" artifact with the full multi-file JSON in raw_contents.
        const [artifact] = await query(`
          INSERT INTO artifacts (project_id, tenant_id, name, artifact_type, metadata)
          VALUES ($1, $2, $3, $4, $5)
          RETURNING *
        `, [
          projectId, 
          tenantId, 
          appName, 
          'website', 
          JSON.stringify({ source_workflow: workflowId, pages_count: files.length })
        ]);

        await query(`
          INSERT INTO artifact_versions (artifact_id, version_number, raw_contents, change_description, summary, created_by)
          VALUES ($1, 1, $2, 'Initial website generation', 'Generated comprehensive Next.js SaaS website with ' || $3 || ' files', 'system')
        `, [artifact.id, JSON.stringify(files, null, 2), files.length]);

        // Emit artifact:created event
        if (runId) {
          runEmitter.emitEvent(runId, 'artifact:created' as any, {
            artifactId: artifact.id,
            filename: artifact.name,
            mimeType: 'website',
            downloadUrl: `/dashboard/workspace?projectId=${projectId}`
          });
        }

        return `Successfully generated Website components (TSX)! Created ${files.length} files. (Artifact ID: ${artifact.id}). Tell the user they can view the fully generated React code in their Artifacts.`;
      } catch (err: any) {
        return `Failed to generate website: ${err.message}`;
      }
    },
    {
      name: "generate_website",
      description: "Generates a full React/Next.js (TSX) application with multiple files/pages. Use this for building comprehensive SaaS websites.",
      schema: z.object({
        appName: z.string().describe("The name of the website or application"),
        files: z.array(z.object({
          filename: z.string().describe("The file path (e.g., 'src/app/page.tsx', 'src/components/Navbar.tsx')"),
          content: z.string().describe("The complete, robust, production-ready TSX/React code for this file")
        })).describe("The array of files to generate for the website")
      }),
    }
  );

  return [generatePresentationTool, generateWebsiteTool];
}
