import { Router, Request, Response } from 'express'
import { authMiddleware, optionalAuth } from '../middleware/auth.middleware'
import { requirePermission, requireRole } from '../middleware/rbac.middleware'
import { rbacService } from '../services/rbac.service'
import { securityAuditLoggerService } from '../services/security-audit-logger.service'
import { dataHandlingPolicyService } from '../services/data-handling-policy.service'

const router = Router()

/**
 * 1. GET /api/security/trust-center
 * Self-serve security and trust overview for enterprise security reviews.
 */
router.get('/trust-center', optionalAuth, (req: Request, res: Response) => {
  const trustReport = {
    overview: {
      productName: 'Chatbolt Polyglot Multi-Agent AI System',
      securityModel: 'Zero-Trust Tripartite Architecture (Node Gateway + Go Runtime + Python Agent-Brain)',
      lastSecurityArchitectureReview: '2026-09-26',
      byokModel: 'Bring-Your-Own-Key with Zero Intermediate Markups or Plaintext Key Persistence',
    },
    encryption: {
      inTransit: 'TLS 1.3 / HTTPS across all external endpoints and internal service boundaries',
      atRest: 'AES-256-GCM authenticated encryption for secrets and customer vault',
      keyDerivation: 'PBKDF2 / SHA-256 with tenant-scoped salting',
      keyRotation: 'Automated re-encryption utility with fail-fast validation',
    },
    accessControl: {
      model: 'Tenant-Level Role-Based Access Control (RBAC)',
      roles: ['owner', 'admin', 'operator', 'auditor', 'viewer'],
      roleCapabilityMatrix: rbacService.getRoleMatrix(),
      serverSideEnforcement: true,
      approvalGates: 'Pre-execution confirmation required for destructive actions and broad filesystem scopes',
    },
    sandboxIsolation: {
      runtimeEngine: 'Go Agent-Runtime Subprocess / Docker Container Sandbox',
      networkPolicy: 'Default-Deny (no outbound network access unless explicitly granted per task)',
      filesystemScope: 'Isolated ephemeral directory per execution with mandatory cleanup',
      secretsProtection: 'Subprocess environment sanitization (all host secrets and tokens stripped)',
      processTermination: 'Hard CPU/RAM memory limits and timeout enforcement',
    },
    auditAndLogging: {
      tamperEvidence: 'Cryptographic SHA-256 Hash Chained Immutable Audit Ledger',
      capturedEvents: [
        'Agent tool invocations and reasoning steps',
        'Human approvals and rejections of sensitive actions',
        'Standing permission rule modifications and revocations',
        'Data access and export events',
        'Authentication and role privilege changes',
      ],
      exportFormats: ['JSON', 'RFC-4180 CSV'],
    },
    dataPrivacyAndRetention: {
      policies: dataHandlingPolicyService.getPolicies(),
      gdprCompliance: 'Right to Erasure / Right to be Forgotten API implemented (POST /api/security/data-purge)',
      dataResidency: 'Tenant data stored in dedicated PostgreSQL partitions / Supabase instances',
    },
    complianceReadiness: {
      statusNotice: 'Architectural controls implemented for SOC 2 Type II, ISO 27001, and GDPR readiness.',
      transparencyDisclaimer:
        'Technical controls provide the engineering foundation for compliance audits. Formal SOC 2 / ISO 27001 certification requires an independent third-party audit firm, an active observation window (3-6 months), operational HR/IT policies, and legal Data Processing Agreements (DPAs). These cannot be generated by software code alone.',
    },
  }

  res.json({ success: true, trustReport })
})

/**
 * 2. GET /api/security/audit-logs
 * Queries immutable security audit logs for the current tenant.
 */
router.get('/audit-logs', authMiddleware, requirePermission('audit:read'), (req: Request, res: Response) => {
  const tenantId = req.tenantId || '00000000-0000-0000-0000-000000000000'
  const { category, userId, resourceType, outcome, from, to, limit, offset } = req.query

  const queryResult = securityAuditLoggerService.queryLogs({
    tenantId,
    category: category as any,
    userId: userId as string,
    resourceType: resourceType as string,
    outcome: outcome as string,
    fromTimestamp: from as string,
    toTimestamp: to as string,
    limit: limit ? parseInt(limit as string, 10) : 50,
    offset: offset ? parseInt(offset as string, 10) : 0,
  })

  // Log the audit read action itself
  securityAuditLoggerService.logEvent({
    tenantId,
    userId: (req as any).user?.id || 'unknown_user',
    userRole: req.userRole,
    category: 'data_access',
    action: 'QUERY_SECURITY_AUDIT_LOGS',
    resourceType: 'audit_ledger',
    resourceId: 'logs',
    outcome: 'success',
    details: { returnedCount: queryResult.records.length, total: queryResult.total },
  })

  res.json({
    success: true,
    ...queryResult,
  })
})

/**
 * 3. GET /api/security/audit-logs/export
 * Exports immutable audit logs to RFC-4180 CSV or JSON.
 */
router.get('/audit-logs/export', authMiddleware, requirePermission('audit:export'), (req: Request, res: Response) => {
  const tenantId = req.tenantId || '00000000-0000-0000-0000-000000000000'
  const format = String(req.query.format || 'json').toLowerCase()

  // Log export to security audit log
  securityAuditLoggerService.logEvent({
    tenantId,
    userId: (req as any).user?.id || 'unknown_user',
    userRole: req.userRole,
    category: 'data_access',
    action: 'EXPORT_SECURITY_AUDIT_LOGS',
    resourceType: 'audit_ledger',
    resourceId: `export_${format}`,
    outcome: 'success',
    details: { format },
  })

  if (format === 'csv') {
    const csv = securityAuditLoggerService.exportToCsv({ tenantId })
    res.setHeader('Content-Type', 'text/csv')
    res.setHeader('Content-Disposition', `attachment; filename="chatbolt_audit_${tenantId}_${Date.now()}.csv"`)
    return res.send(csv)
  }

  const result = securityAuditLoggerService.queryLogs({ tenantId, limit: 10000 })
  res.json({ success: true, exportTimestamp: new Date().toISOString(), ...result })
})

/**
 * 4. GET /api/security/data-inventory
 * Returns the current tenant's data footprint and retention status.
 */
router.get('/data-inventory', authMiddleware, requirePermission('security:view_trust_center'), async (req: Request, res: Response) => {
  const tenantId = req.tenantId || '00000000-0000-0000-0000-000000000000'
  const inventory = await dataHandlingPolicyService.getDataInventory(tenantId)
  res.json({ success: true, inventory })
})

/**
 * 5. POST /api/security/data-purge
 * Enforces GDPR Right to be Forgotten / Tenant Data Purge.
 */
router.post('/data-purge', authMiddleware, requirePermission('security:data_purge'), async (req: Request, res: Response) => {
  const tenantId = req.tenantId || '00000000-0000-0000-0000-000000000000'
  const userId = (req as any).user?.id || 'unknown_user'
  const scope = req.body.scope || 'all'

  const purgeResult = await dataHandlingPolicyService.purgeTenantData(tenantId, userId, scope)
  res.json({ success: true, ...purgeResult })
})

/**
 * 6. GET /api/security/compliance-status
 * Delivers honest compliance posture, evidence mapping, and non-engineering workstream budget.
 */
router.get('/compliance-status', optionalAuth, (req: Request, res: Response) => {
  const complianceStatus = {
    evaluatedStandards: {
      soc2_type_2: {
        readinessStatus: 'ARCHITECTURALLY_READY',
        implementedControls: [
          'CC6.1: Role-Based Access Control (RBAC) with server-side enforcement',
          'CC6.6: Default-deny network isolation and sandboxed code execution',
          'CC6.7: AES-256-GCM data encryption at rest and TLS 1.3 in transit',
          'CC6.8: SHA-256 chained immutable audit logging with RFC-4180 export',
          'CC7.2: Real-time telemetry, error monitoring, and security alerting',
        ],
        requiredNonEngineeringSteps: [
          'Engage an accredited AICPA CPA audit firm (e.g. Vanta/Drata + Schellman/A-LIGN)',
          'Complete 3-to-6 month observation period with continuous evidence collection',
          'Formalize company-wide IT policies (Employee onboarding/offboarding, MDM, Background checks)',
          'Conduct third-party penetration testing by a certified CREST/OSCP red team',
        ],
        estimatedBudgetUsd: {
          auditFirmFees: '$15,000 - $35,000',
          complianceAutomationPlatform: '$8,000 - $15,000/yr',
          annualPenetrationTest: '$6,000 - $12,000',
        },
      },
      iso_27001_2022: {
        readinessStatus: 'ARCHITECTURALLY_READY',
        implementedControls: [
          'A.8.24: Cryptographic key management and vault isolation',
          'A.8.20: Network segregation and lateral-movement prevention in Go sandbox',
          'A.8.12: Data leakage prevention (DLP) secrets sanitization across all logs',
          'A.8.31: Separation of dev, test, and production runtime environments',
        ],
        requiredNonEngineeringSteps: [
          'Establish Information Security Management System (ISMS) and Statement of Applicability (SoA)',
          'Internal audit execution and management review meeting',
          'Stage 1 (Documentation Review) and Stage 2 (Certification Audit) by an accredited registrar (BSI, TÜV, ISOQAR)',
        ],
        estimatedBudgetUsd: {
          registrarAuditFees: '$12,000 - $25,000',
          consultingAndPrep: '$10,000 - $20,000',
        },
      },
      gdpr_ccpa: {
        readinessStatus: 'TECHNICAL_CONTROLS_ACTIVE',
        implementedControls: [
          'Article 17: Right to Erasure / Right to be Forgotten API (`POST /api/security/data-purge`)',
          'Article 25: Data protection by design and default (ephemeral execution files, client-controlled memory)',
          'Article 32: State-of-the-art encryption and pseudonymization of tenant embeddings',
        ],
        requiredNonEngineeringSteps: [
          'Standard Contractual Clauses (SCCs) and Data Processing Agreements (DPAs) with enterprise buyers',
          'Designation of Data Protection Officer (DPO) or EU/UK representative if processing EU resident data',
          'Record of Processing Activities (ROPA) documentation',
        ],
      },
    },
    transparencyPledge:
      'Chatbolt does not make unverified compliance claims. Our software provides all requisite technical controls out-of-the-box, but formal certifications require the non-engineering workstreams detailed above.',
  }

  res.json({ success: true, complianceStatus })
})

export default router
